### PR TITLE
add a basic footer

### PR DESCRIPTION
**Pull request by Meden-Agan-27**
Please review the code

### CODE REVIEW

**Comment by Meden-Agan-27** [comment]
@madan1101 
What I did: insert a minimal footer.
How to test it: open local host and see if it appears

**Comment by madan1101** [comment]
I am trying to view your footer.

**Comment by madan1101** [comment]
Screen Shot 2020-03-17 at 2 14 47 PM

The footer is not at the bottom of the page. Is this only temporary?

**Comment by Meden-Agan-27** [comment]
@madan1101 Yes, it is because there is no content yet. I tried with fake-text and it was at the bottom. Glad that you can see it! It is magical!!

**Comment by madan1101** [comment]
Looks great, love the color!

**Pull request merged**
