### PR TITLE
Reshape pet model

### PR DESCRIPTION
**Pull request by tarcea**
I did:
1. pet model wit the new columns, associations and validation(we can add more validations later on)  
2. seeds
3. in user controller I added dependent: : destroy for pets
how to test:
"1" you can pull the code, run the seed and try email: "woland@sisi.com", password: "123456"
look at the code and at schema
"2" run the seeds
"3" run the seeds several times, should have no errors

### CODE REVIEW

**Comment by Meden-Agan-27** [comment]
@tarcea I can't destroy user because of the dependency.
I can't find that in your coede : in user Model I added dependent: : destroy for pets

**Comment by tarcea** [comment]
check now

**Comment by Meden-Agan-27** [comment]
@tarcea you have to push it again

**Comment by Meden-Agan-27** [comment]
All good now!

**Pull request merged**
