### PR TITLE
Cloudify integration

### PR DESCRIPTION
**Pull request by sano2019**
What I did:
Added cloudify integration and created seeds that work for cloudify.

How to test:
Please run the following command after pulling this branch:
rails db:drop db:create db:migrate db:seed

Seeding will take a little while because of the API connection.

After confirming the index works, please try to add a new pet and upload a local image with it.

### CODE REVIEW

**Comment by madan1101** [comment]
Do I choose an image from the Images folder to upload?

**Comment by madan1101** [comment]
Screen Shot 2020-03-19 at 5 09 12 PM

**Comment by madan1101** [comment]
plz delete old code in seeds.rb to resolve conflict

**Comment by sano2019** [comment]
Updated the seeds and re-pushed to github

**Pull request merged**
